/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    A11yAnnouncer: typeof import('./../components/common/A11yAnnouncer.vue')['default']
    A11yWrapper: typeof import('./../components/common/A11yWrapper.vue')['default']
    AppHeader: typeof import('./../components/layout/AppHeader.vue')['default']
    AppLayout: typeof import('./../components/layout/AppLayout.vue')['default']
    AppSidebar: typeof import('./../components/layout/AppSidebar.vue')['default']
    AudioPlayer: typeof import('./../components/business/AudioPlayer.vue')['default']
    CameraCapture: typeof import('./../components/business/CameraCapture.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBadge: typeof import('element-plus/es')['ElBadge']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDescriptions: typeof import('element-plus/es')['ElDescriptions']
    ElDescriptionsItem: typeof import('element-plus/es')['ElDescriptionsItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    EmptyState: typeof import('./../components/common/EmptyState.vue')['default']
    LoadingMask: typeof import('./../components/common/LoadingMask.vue')['default']
    MatrixRain: typeof import('./../components/common/MatrixRain.vue')['default']
    RecognitionCard: typeof import('./../components/business/RecognitionCard.vue')['default']
    ResultDisplay: typeof import('./../components/business/ResultDisplay.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SkipLink: typeof import('./../components/common/SkipLink.vue')['default']
    VoiceButton: typeof import('./../components/business/VoiceButton.vue')['default']
  }
}
